user = input("Ingresa tu nombre de usuario: ")
age = int(input("Ingresa tu edad: "))
bio = input("biografía: ")
folowers = int(input("Ingresa tu número de seguidores: "))
emoj = input("Ingresa tu emoji favorito: ")
print("°" * 45)
print("")

print(f"🎭", {user})
print(f"🔞", {age}, "años")
print(f"📝", {bio})
print(f"👥", {folowers}, "seguidores")
print(f"😃", "Emoji favorito", {emoj})
print("")
print("°" * 45)